### PR TITLE
Change `ListJobs` to return `JobID` and `JobState`

### PR DESCRIPTION
**Pull request by jeenalee**
~**blocked by https://github.com/ga4gh/task-execution-schemas/pull/20**
Once https://github.com/ga4gh/task-execution-schemas/pull/20 is merged, protobuf needs to be rebuilt, and included in this PR.~
Edit: This PR is no longer blocked by the schema change PR.

This patch modifies `ListJobs` to return an array of `JobID` and `JobState` (grouped together as `JobDesc` rather than `Jobs`, making it faster and more concise.

---

- [X] `make` does not report any errors
- [X] `make tidy` does not report any errors (except for package name related errors)
- [ ] These changes fix #__ (github issue number if applicable).

- [X] There are documentation for these changes OR
- [ ] These changes do not require documentation because _____

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because minor refactor

### CODE REVIEW

**Comment by buchanae** [comment]
What's driving the need for this change? Is this primarily a performance enhancement?

Will this affect the web dashboard? For example, does it now need to get a list of job IDs and then make secondary queries for each of those job IDs?

**Comment by jeenalee** [comment]
This change was suggested by @kellrott. I believe it's primarily for making the function to list jobs faster -- instead of listing the complete information of the jobs, it will list just the job IDs.

> Will this affect the web dashboard? For example, does it now need to get a list of job IDs and then make secondary queries for each of those job IDs?

I'm not sure about this, but my guess is yes. Maybe Kyle can clarify?

Is `ListJobs` called in TES? I thought it's not a used function yet.

**Comment by kellrott** [comment]
Probably need to update the submodule link to task-execution-schemas and rebuild the _pb.go files to get this to pass Travis tests.

**Comment by jeenalee** [comment]
Yup, will do.

**Comment by kellrott** [comment]
Checks pass on Travis. Accepting.

**Pull request merged**
