### PR TITLE
Ubermerge: storage backend, slots, and more

### PR DESCRIPTION
**Pull request by buchanae**
So, with all the activity this week, we ended up with a couple branches with lots of changes, and this should be merging all those at once, which I think is easier than bothering to pull them all apart into smaller PRs.

Here's the rundown:
- tes-server can pull config from a YAML file
- fork_engine was rewritten to slots/pool
- tes worker storage was rewritten with a better interface for pluggable storage backends. Local storage and S3 exist.
- Minio was added for support S3 storage
- A test framework which includes S3/minio was started, along with related python code and examples.
- communication with the worker (Protobuf + server api) was updated to include S3 auth information. This is still a very rough prototype.
- the web dashboard was fixed.
- A scheduler client library was started (attempting to extract frequently repeated code into something reuable)
- FileMapper was substantially refactored during the storage rewrite.
- FileMapper is no longer responsible for download/upload (that moved to the engine). The FileMapper is now only responsible for mapping job paths into a job-specific working directory.
- FileMapper maps paths mainly by appending the input path to the job-specific working directory.
- The worker engine changed substantially to accommodate new responsibilities related to the storage rewrite, including getting auth information, getting a job-specific file mapper, download/uploading inputs/outputs, and communicating updates to the scheduler.
- Lots of updates to documentation.
- submodules have been added and pruned
- some dev tasks in Makefile have been fixed and added: tidy, add_deps, prune_deps, serve_doc
- ./buildtools was added to the Makefile gopath in an attempt to keep the src directory free of packages downloaded by `go get`. Seems to work so far.

### CODE REVIEW

**Comment by buchanae** [comment]
This will close #34 and #23 and possibly #21

**Comment by kellrott** [comment]
Can you update the .travis.yml file to do the pip installs needed for running the unit tests?

**Comment by buchanae** [comment]
There are a few things to follow up on, and for lack of a better place, I'll dump them here:

1) JWT and auth. JWT isn't encrypted, and I'm not sure it makes sense to have JWT code in the worker. Also, we'll need to design how secrets are stored in the TES server. We should look at Vault. Also, how is a secret key shared between TES master and worker? Does that even make sense?

2) I implemented the "allowed dirs" config in the local FS storage backend, but I see the test code and config going with a basedir. We should talk about going with one or both. In general, I think having flexible per-user, per-job storage that isn't confined by a single server config needs some discussion. 

3) The py_tes library made the s3 test much cleaner. Would be nice to continue extending this to the other tests and to centralize the python code under one directory.

4) I'd love to see a full suite of conformance tests. This is a reference implementation after all, and the best way to determine whether an implementation of TES is correct is with coded tests. We're starting to get into the some more complex details (storage paths, config, auth, users, etc) which are hard to write in english but easier to write in python.

5) I think `make tidy` wasn't running correctly before, so there are now a lot of messages from that command

6) I've had a lot of issues with the dev/build/test environment, and I know Jeena has had at least one issue ( #40 ). Lets use docker to make dev. as quick and easy as possible. Specifically, I'd like it if new developers don't need to worry about installing go, protoc, make, python, pip, etc.

7) I have the s3 endpoint hard-coded. I need to fix that. This relates to 2)

8) There's an awkward mix of config happening via CLI vs YAML. Probably want to clean that up at some point.

9) When a task is submitted, if Task.Docker.Stdout is blank, should Stdout still be logged back to the TES server? I think it was that way before, and I may have broken that in this PR. This is one of those details that that 4) would help with.

10) Still curious why the docker command uses "-i"

I know that's a long list, but it's over a week worth of thoughts that needed to be collected. I can break them into separate issues after some initial discussion.

**Comment by buchanae** [comment]
Pull request was merged with @kellrott in person, and since we were at my computer, it just happened to be easier to merge this from my account.

We discussed the issues mentioned about (1-10). I'll file separate issues for some of them tomorrow.

**Pull request merged**
