### PR TITLE
Add `.github` directory with pull request template

### PR DESCRIPTION
**Pull request by jeenalee**
This patch adds a pull request template for TES. Future contributors should use this template to ensure standardized pull requests that are easier to keep track of. 

You may read more about `.github` directory [here](https://github.com/blog/2111-issue-and-pull-request-templates).

### CODE REVIEW

**Comment by jeenalee** [comment]
Weirdly, Kyle's commits were all included in this PR. I'll open a separate one that contains only my changes.

**Comment by kellrott** [comment]
Sorry, I think I was merging stuff in for the hackathon and accidentally grabbed your changes.

**Comment by jeenalee** [comment]
@kellrott Are we supposed to push changes to `develop` or `master`?

**Comment by jeenalee** [comment]
I created the branch from `bmeg:master` instead of `bmeg:develop`. I made a new PR that was branched from `bmeg:develop`.

**Pull request closed without merging**
